### ISSUE TITLE
Allow translations of left right cards resource

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-unplugged#509]
Created from #484.

**Comment by jordangriffiths01** [comment]
@saranglove the SVG you gave me for this didn't have rectangle elements defining the text box areas, it looks like you might have added text elements directly rather than into a bounding box. Did you follow [this process](http://cs-unplugged.readthedocs.io/en/develop/developer/resources.html#creating-a-new-dynamic-text-field)?

**Comment by saranglove** [comment]
I'm pretty sure I did because I remember having a conversation with you about the naming conventions for it. But I'll make another one.

**Comment by JackMorganNZ** [comment]
Completed in #898
